name: rename-secrets-hostname
on:
  push:
    branches: [feat/rename-secrets-hostname]
permissions:
  contents: write
jobs:
  rename:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {ref: feat/rename-secrets-hostname}
      - run: |
          grep -RIl 'pwd\.1ms\.my' . --exclude-dir=.git --exclude=rename-secrets-hostname.yml | xargs -r sed -i 's/pwd\.1ms\.my/secrets.1ms.my/g'
          rm .github/workflows/rename-secrets-hostname.yml
          git config user.name 'GitHub Actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'refactor: rename secrets hostname'
          git push origin HEAD:feat/rename-secrets-hostname
